### PR TITLE
Make option 'main' accept an array

### PR DESCRIPTION
**Pull request by jpeltoniemi**
I needed to be able to compile both production and development versions from parly the same source files that are modified all the time. In my case if would've been more efficient to allow both 'out' and 'main' simultaneously to allow an additional layer of variable overrides and such, but this was faster to do.

### CODE REVIEW

**Comment by schmuli** [comment]
I can merge this now, but I want to point out that my plan is to change atom-less to use a project configuration file, and I'm not sure how such a feature would work then.

**Comment by jpeltoniemi** [comment]
Thanks! I assume the project configuration file would also handle situations where the same source files contribute to more than one compiled stylesheet?

**Comment by schmuli** [comment]
I haven't thought about that scenario, since this is not something I have needed. I would appreciate if you could describe one or more use cases for this feature.

**Comment by jpeltoniemi** [comment]
It's not really a big deal, but I have 2 main files - one for production and one for development. Both include the same files, but the development version includes some more files and may change some variables for easier debugging. With this commit, I can have both compiled automatically whenever I change any of the included files.

Like I said, not that big of a deal. Though if you want and it's not too much trouble, you could design the new configuration system so something like this could be added later with relative ease :)

**Pull request merged**
